export { default as HeroSection } from './HeroSection'
export { default as WelcomeSection } from './WelcomeSection'
export { default as BusinessesSection } from './BusinessesSection'
export { default as TeamSection } from './TeamSection'
export { default as AwardsSection } from './AwardsSection'
export { default as LocationsSection } from './LocationsSection'
export { default as CTASection } from './CTASection'
export { default as Footer } from './Footer'